language: python

python:
  - 3.6

services: postgresql

env:
  - DJANGO=2.2.1

before_install:
  - export DJANGO_SETTINGS_MODULE=your_project.settings
  - export PYTHONPATH=$HOME/builds/raidu4u/colaberrylabs
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

script:
  - python manage.py runserver